export const CONFLICT_ERROR = 409;
export const INTERNAL_SERVER_ERROR = 500;
export const CONFLICT_MESSAGE = "Пользователь с таким email уже существует.";
export const INTERNAL_SERVER_MESSAGE = "Внутренняя ошибка сервера, попробуйте позднее.";
export const DEFAULT_MESSAGE_REGISTER = "Очень жаль, произошла ошибка при регистрации пользователя.";
export const DEFAULT_MESSAGE_LOGIN = "Очень жаль, произошла ошибка при авторизации пользователя.";
export const DEFAULT_MESSAGE_UPDATE = "Очень жаль, произошла ошибка при изменении данных пользователя.";
export const WELCOME_MESSAGE = "Добро пожаловать!";
export const SUCCESSFUL_UPDATE_MESSAGE = "Данные профиля успешно обновлены!";
